CREATE TABLE gwas (
	date_added_to_catalog DATE,
	pubmedid VARCHAR(1024),
	first_author VARCHAR(1024),
	date DATE,
	journal VARCHAR(1024),
	link VARCHAR(1024),
	study VARCHAR(1024),
	disease_trait VARCHAR(1024),
	initial_sample_size VARCHAR(1024),
	replication_sample_size VARCHAR(1024),
	platform_snps_passing_qc VARCHAR(1024),
	association_count INT,
	mapped_trait VARCHAR(1024),
	mapped_trait_uri VARCHAR(1024),
	study_accession VARCHAR(16),
	genotyping_technology VARCHAR(1024)
);
CREATE TABLE assn (
	date_added_to_catalog DATE,
	pubmedid VARCHAR(1024),
	first_author VARCHAR(1024),
	date DATE,
	journal VARCHAR(1024),
	link VARCHAR(1024),
	study VARCHAR(1024),
	disease_trait VARCHAR(1024),
	initial_sample_size VARCHAR(1024),
	replication_sample_size VARCHAR(1024),
	region VARCHAR(16),
	chr_id VARCHAR(8),
	chr_pos VARCHAR(16),
	reported_genes VARCHAR(1024),
	mapped_gene VARCHAR(1024),
	upstream_gene_id VARCHAR(12),
	downstream_gene_id VARCHAR(12),
	snp_gene_ids VARCHAR(1024),
	upstream_gene_distance INT,
	downstream_gene_distance INT,
	strongest_snp_risk_allele VARCHAR(16),
	snps VARCHAR(16),
	merged CHAR(1),
	snp_id_current VARCHAR(16),
	context VARCHAR(32),
	intergenic CHAR(1),
	risk_allele_frequency FLOAT,
	p_value FLOAT,
	pvalue_mlog FLOAT,
	p_value_text VARCHAR(1024),
	or_or_beta FLOAT,
	ci_95_text VARCHAR(1024),
	platform_snps_passing_qc VARCHAR(64),
	cnv CHAR(1),
	mapped_trait VARCHAR(1024),
	mapped_trait_uri VARCHAR(1024),
	study_accession VARCHAR(16),
	genotyping_technology VARCHAR(1024),
	oddsratio FLOAT,
	beta FLOAT
);
CREATE TABLE snp2gene (
	study_accession VARCHAR(16),
	gsymb VARCHAR(16),
	snp VARCHAR(32),
	reported_or_mapped VARCHAR(4)
);
CREATE TABLE trait (
	study_accession VARCHAR(16),
	mapped_trait VARCHAR(1024),
	mapped_trait_uri VARCHAR(128)
);
CREATE TABLE icite (
	authors MEDIUMTEXT,
	title MEDIUMTEXT,
	citations_per_year FLOAT,
	relative_citation_ratio FLOAT,
	year INT,
	is_research_article BOOLEAN,
	nih_percentile FLOAT,
	citation_count INT,
	journal VARCHAR(1024),
	field_citation_rate FLOAT,
	expected_citations_per_year FLOAT,
	pmid INT
);
CREATE TABLE gt_stats (
	gsymb VARCHAR(16),
	trait_uri VARCHAR(1024),
	trait VARCHAR(1024),
	n_study INT,
	n_snp INT,
	n_traits_g INT,
	n_genes_t INT,
	pvalue_mlog_median FLOAT,
	or_median FLOAT,
	tdl VARCHAR(8),
	fam VARCHAR(16),
	idg2 BOOLEAN,
	name VARCHAR(1024)
);
